# Generated by Django 2.1.3 on 2018-11-03 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='icon',
            field=models.CharField(max_length=100),
        ),
    ]
