# Generated by Django 2.1.3 on 2018-11-03 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('abstract_pt', models.TextField(blank=True)),
                ('abstract_en', models.TextField(blank=True)),
                ('link', models.CharField(max_length=255)),
            ],
        ),
    ]
